version: "3"
services:
  api:
    build: ./api
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./api/api:/code
  database:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${PROJECT_NAME}
      POSTGRES_DB: ${PROJECT_NAME}
