version: "3"
services:
  api:
    build: ./api
    depends_on:
      - database
    ports:
      - "5000:5000"
    env_file:
      - api.env
    volumes:
      - ./api/api:/code
  database:
    image: postgres
    expose:
      - "5432"
    env_file:
      - database.env
